title: "({shakyshane.com})"
s3prefix: "https://s3-eu-west-1.amazonaws.com/shakshane/"
css:
  dev: /css/main.css
  production: main.min-d106a42e.css
navigation:
  - title: "Blog"
    url  : "/blog"
  - title: "Projects"
    url  : "/projects"


projects:
  - name: "BrowserSync"
    url: "http://www.browsersync.io/"
    github: "https://github.com/shakyShane/browser-sync"
    desc: >
      Keep multiple browsers & devices in sync when building websites.
  - name: "crossbow.js"
    url: "http://www.crossbow.io/"
    github: "https://github.com/shakyShane/crossbow"
    desc: >
      the fastest, most feature-rich static-site generator + blog.

